Refactor Upload Location and Return Type of the API
dot-base/file-storage-api pull request #18
Opened 2021-09-09 12:48 UTC by defo10

### 🚀 Feature Description
This PR refactors the file storage api endpoint which now includes the context and corresponding fhir id of the patient. The api returns a fhir attachment, now. This resolves #16 .

### 🧰 Technical Solution
- [x] Change endpoints
- [x] Give uuid to new file
- [x] return fhir attachment

2021-09-24 08:31 UTC, friedow requested changes

2021-09-24 08:31 UTC, friedow commented on src/utils/FileUpload.ts
> +      ? `./${context}/${fhirId}`
**[security relevant]** All parameters that are placed in a URL, SQL Query or File System Path MUST be escaped. Otherwise I could construct a `fhirId` like `../boot` and break out of the context directory.

2021-09-24 08:31 UTC, friedow commented on src/utils/FileUpload.ts
> +        "Invalid file type. The server only accepts files with one the following extensions: jpg, json, mp4, pdf, ply or png."
Please convert the list of accepted extensions into a static getter in this class. (Since it is used here and to check the extensions as well.)

2021-09-24 08:31 UTC, friedow commented on src/utils/FileUpload.ts
> +      process.env.NODE_ENV === "development" || process.env.INSECURE ? "http://" : "https://";
Lets reduce that to:
```suggestion
    const protocol =
      process.env.NODE_ENV === "development" ? "http://" : "https://";
```

2021-11-23 11:51 UTC, andreakreichgauer approved these changes
Nice work :+1:

2021-11-23 12:29 UTC, merged