enforce setting mime type
dot-base/file-storage-api pull request #27
Opened 2021-12-16 13:17 UTC by andreakreichgauer

This fixes the upload for ply files. Currently `application/octet-stream` was set as default type. As a result ply files are not displayed frontend-wise.

2021-12-16 15:35 UTC, friedow requested changes

2021-12-16 15:35 UTC, friedow commented on src/services/FileService.ts
> +        return "application/octet-stream";
The mime types returned here do not match the list of common mime types for files: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types.
Please adjust this accordingly.

2021-12-16 15:35 UTC, friedow commented on src/services/FileService.ts
> +      if (file.type === "application/octet-stream") file.type = this.setMimeType(file.path);
Why is setMimeType only called on `application/octet-stream` even though it specifies mime types for all file endings?

2021-12-16 15:42 UTC, andreakreichgauer commented on src/services/FileService.ts
> +      if (file.type === "application/octet-stream") file.type = this.setMimeType(file.path);
Formidable seems to set application/octet-stream as default if no type is specified by the client (as currently for ply files).

2021-12-17 09:39 UTC, friedow approved these changes

2021-12-17 09:41 UTC, merged